#!/usr/bin/env node

var operation = process.argv[2];
var answer;
var n2 = +process.argv[4];
var n1 = +process.argv[3];

switch(operation){
	case "add":
		answer = add(n1, n2);
		break;
	case "subtract":
		answer = subtract(n1, n2);
		break;
	case "multiply":
		answer = multiply(n1, n2);
		break;
	case "divide":
		answer = divide(n1, n2);
		break;
	default:
		answer = "Invalid operation.";
		break;
}
console.log(answer);

function add(a, b) {
	return (a + b);
};

function subtract(a, b) {
	return (a - b);
};

function multiply(a, b) {
	return (a * b);
};

function divide(a, b) {
	if(0 === b)
		return "Undefined.";
	else 
		return (a / b);
};

exports.add = add;
exports.subtract = subtract;
exports.multiply = multiply;
exports.divide = divide;

/*exports.divide = function(a, b) {
	if(0 === n2)
		return "Undefined."
	else 
		return n1 / n2;
};
*/
